---
directory_mapping:
  - source: "{{ playbook_dir }}/alacritty"
    target: "{{ development_machine_xdg_config_home }}/alacritty"
  - source: "{{ playbook_dir }}/helix"
    target: "{{ development_machine_xdg_config_home }}/helix"
  - source: "{{ playbook_dir }}/neovim"
    target: "{{ development_machine_xdg_config_home }}/nvim"
  - source: "{{ playbook_dir }}/starship"
    target: "{{ development_machine_xdg_config_home }}/starship"
  - source: "{{ playbook_dir }}/vim"
    target: "{{ development_machine_xdg_config_home }}/vim"
  - source: "{{ playbook_dir }}/wezterm"
    target: "{{ development_machine_xdg_config_home }}/wezterm"
  - source: "{{ playbook_dir }}/zsh"
    target: "~"
