theme = "rose_pine"

[editor]
line-number = "relative"
rulers = [80]
idle-timeout = 33
color-modes = true
auto-save = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"

[editor.whitespace.characters]
nbsp = "␣"
nnbsp = "␣"
space = "·"
tab = "»"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true

[keys.normal]
C-e = "scroll_down"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-s = ":update"
C-y = "scroll_up"
ret = "goto_word"

[keys.normal.space]
w = {c = ":buffer-close"}
