theme = "rose_pine"

[editor]
auto-save = true
color-modes = true
end-of-line-diagnostics = "hint"
idle-timeout = 33
line-number = "relative"
rulers = [80]

[editor.file-picker]
hidden = false  # Do not ignore hidden files

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"

[editor.soft-wrap]
enable = true

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
0 = "goto_line_start"
C-e = "scroll_down"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-s = ":update"
C-y = "scroll_up"
G = 'goto_file_end'
N = ["search_prev", "align_view_center"]
V = ["select_mode","extend_to_line_bounds"]
esc = ["collapse_selection","keep_primary_selection"]
n = ["search_next", "align_view_center"]
ret = "goto_word"

[keys.normal.space]
w = {c = ":buffer-close"}

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
0 = "goto_line_start"
D = ["extend_to_line_bounds","delete_selection", "normal_mode"]
G = 'goto_file_end'
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
