---
- name: Brew packages installed
  community.general.homebrew:
    state: latest
    package:
      - anomalyco/tap/opencode
      - btop
      - fd
      - fzf
      - go-task
      - helix
      - jq
      - lazygit
      - neovim
      - ripgrep
      - starship
      - uv
      - vim
      - yq
