---
- name: "Check {{ font.name_prefix }}*.ttf existance"
  register: development_machine_font_files
  ansible.builtin.find:
    paths: "{{ dest_per_system[ansible_facts['system']] }}"
    patterns: "{{ font.name_prefix }}*.ttf"
- name: "Unarchive {{ font.archive }}"
  when: not development_machine_font_files.matched
  ansible.builtin.unarchive:
    dest: "{{ dest_per_system[ansible_system] }}"
    remote_src: true
    src: >-
      https://github.com/ryanoasis/nerd-fonts/releases/download/{{ version
      }}/{{ font.archive }}
