---
- name: Include link sources and destinations
  ansible.builtin.include_vars:
    file: config-links.yml
- name: Stow config files
  ansible.builtin.include_tasks:
    file: stow.yml
    apply:
      tags:
        - configs
  loop: "{{ development_machine_directory_mapping }}"
  loop_control:
    loop_var: app_config
  vars:
    src_dir: "{{ app_config.source }}"
    target_dir: "{{ app_config.target }}"
  tags:
    - configs
