---
- name: Find sources in {{ src_dir }}
  register: development_machine_sources
  ansible.builtin.find:
    file_type: any
    hidden: true
    paths: "{{ src_dir }}"
- name: Target directory {{ target_dir }}
  ansible.builtin.file:
    path: "{{ target_dir }}"
    state: directory
    mode: "0755"
- name: Symlinks in {{ target_dir }}
  ansible.builtin.file:
    path: "{{ target_dir }}/{{ file_path | basename }}"
    src: "{{ file_path }}"
    state: link
  loop: "{{ development_machine_sources.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: file_path
