---
- name: macOS packages installed
  community.general.homebrew:
    state: latest
    package:
      - bat
      - btop
      - fd
      - fzf
      - go-task
      - jq
      - lazygit
      - neovim
      - ripgrep
      - starship
      - uv
      - vim
      - yq
